[package]
name = "valorant-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.25", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
serde_json = "1.0.82"
base64 = "0.22.0"
dirs = "5.0.1"
